name: "Vig_Lentner"

on: 
  schedule:
    - cron:  '* /12 * * *'

jobs:
  download-data:
    runs-on: windows-latest
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update dropbox
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: |
        python download_data.py
        git config --global user.email "gh-actions@github.com"
        git config --global user.name "github actions"
  data-processing:
    runs-on: windows-latest
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: data processing
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: |
        python data_processing.py
        git config --global user.email "gh-actions@github.com"
        git config --global user.name "github actions"
    
